<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-LG2LKO2" failures="1" tests="4" name="retryTest(failed)" time="0.11" errors="0" timestamp="2020-01-05T12:59:38 IST">
  <testcase classname="reexecutefailtestcase.failtestcase" name="test1" time="0.02">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="reexecutefailtestcase.failtestcase" name="test1" time="0.0">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="reexecutefailtestcase.failtestcase" name="test1" time="0.005">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="reexecutefailtestcase.failtestcase" name="test1" time="0.005">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at reexecutefailtestcase.failtestcase.test1(failtestcase.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="reexecutefailtestcase.failtestcase" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- retryTest(failed) -->
